version: '3.9'
services:
  backend:
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - ENV=development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis

  celery:
    command: celery -A app.main.celery_app worker --loglevel=info --concurrency=1 --pool=solo
    environment:
      - ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

  frontend:
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
