"""Initial migration

Revision ID: e30a12487533
Revises: 
Create Date: 2025-05-26 12:34:59.586114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'e30a12487533'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_enrichment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('enrichment_type', sa.String(), nullable=False),
    sa.Column('enriched_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_metric', sa.String(), nullable=True),
    sa.Column('target_value', sa.NUMERIC(), nullable=True),
    sa.Column('current_value', sa.NUMERIC(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('type', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('document_status', sa.String(), nullable=True),
    sa.Column('lpa_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('baseline_scenario_id', sa.UUID(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('summary_metrics', sa.JSON(), nullable=True),
    sa.Column('included_site_ids', sa.JSON(), nullable=True),
    sa.Column('excluded_site_ids', sa.JSON(), nullable=True),
    sa.Column('active_policy_ids', sa.JSON(), nullable=True),
    sa.Column('modified_policies', sa.JSON(), nullable=True),
    sa.Column('goal_performance', sa.JSON(), nullable=True),
    sa.Column('soundness_flags', sa.JSON(), nullable=True),
    sa.Column('ai_commentary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('uprn', sa.String(), nullable=True),
    sa.Column('lpa_code', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_ha', sa.REAL(), nullable=True),
    sa.Column('plan_making_status', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('deliverability_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soundness_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sites_geom', 'sites', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('source_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('sha256_hash', sa.String(), nullable=True),
    sa.Column('lpa_code', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('write_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('output_type', sa.String(), nullable=False),
    sa.Column('source_entity', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order_no', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.TIMESTAMP(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['plan_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_text_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('proposal_details', sa.Text(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('applicant_name', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('case_officer', sa.String(), nullable=True),
    sa.Column('planner_weightings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lpa_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.Column('policy_title', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('cross_references', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('geographic_mentions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('lpa_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['plan_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_ai_context',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('retrieval_log_id', sa.UUID(), nullable=True),
    sa.Column('reasoning_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competing_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['planning_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieval_log_id'], ['retrieval_logs.log_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('application_material_refs',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('material_code', sa.String(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['planning_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'material_type', 'material_code')
    )
    op.create_table('application_vectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['planning_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['extracted_text_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constraints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_policy_id', sa.UUID(), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['source_policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_constraints_geom', 'constraints', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('policy_cross_links',
    sa.Column('source_policy_code', sa.String(), nullable=False),
    sa.Column('target_policy_code', sa.String(), nullable=False),
    sa.Column('source_policy_id', sa.UUID(), nullable=True),
    sa.Column('target_policy_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['source_policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('source_policy_code', 'target_policy_code')
    )
    op.create_table('policy_vectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('policy_ref', sa.String(), nullable=True),
    sa.Column('key_themes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cross_references', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('geographic_mentions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['extracted_text_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precedent_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('outcome', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['planning_applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derived_geographic_constraints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_name', sa.String(), nullable=False),
    sa.Column('constraint_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['constraint_id'], ['constraints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officer_reports',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('ai_context_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_by', sa.String(), nullable=True),
    sa.Column('last_modified', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ai_context_id'], ['application_ai_context.application_id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['planning_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('precedent_key_policies',
    sa.Column('precedent_id', sa.UUID(), nullable=False),
    sa.Column('policy_code', sa.String(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['precedent_id'], ['precedent_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('precedent_id', 'policy_code')
    )
    op.create_table('precedent_vectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_case_id', sa.UUID(), nullable=True),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_policies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('site_context', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['source_case_id'], ['precedent_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officer_report_sections',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('agent_stage', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['officer_reports.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.drop_index(op.f('idx_chunk_embeddings_embedding'), table_name='chunk_embeddings', postgresql_using='hnsw')
    op.drop_table('chunk_embeddings')
    op.drop_table('documents')
    op.drop_table('spatial_ref_sys')
    op.drop_table('document_chunks')
    op.add_column('retrieval_logs', sa.Column('retrieval_target', sa.String(), nullable=True))
    op.alter_column('retrieval_logs', 'matched_chunk_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('retrieval_logs', 'agent_context',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retrieval_logs', 'agent_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('retrieval_logs', 'matched_chunk_ids',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.UUID()),
               existing_nullable=True)
    op.drop_column('retrieval_logs', 'retrieval_target')
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('doc_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], name='document_chunks_doc_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', name='document_chunks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('documents',
    sa.Column('doc_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('doc_id', name='documents_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chunk_embeddings',
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding', Vector(dim=768), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.chunk_id'], name=op.f('chunk_embeddings_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('chunk_embeddings_pkey'))
    )
    op.create_index(op.f('idx_chunk_embeddings_embedding'), 'chunk_embeddings', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_table('officer_report_sections')
    op.drop_table('precedent_vectors')
    op.drop_table('precedent_key_policies')
    op.drop_table('officer_reports')
    op.drop_table('derived_geographic_constraints')
    op.drop_table('precedent_cases')
    op.drop_table('policy_vectors')
    op.drop_table('policy_cross_links')
    op.drop_index('idx_constraints_geom', table_name='constraints', postgresql_using='gist')
    op.drop_table('constraints')
    op.drop_table('application_vectors')
    op.drop_table('application_material_refs')
    op.drop_table('application_ai_context')
    op.drop_table('policies')
    op.drop_table('planning_applications')
    op.drop_table('extracted_text_chunks')
    op.drop_table('document_nodes')
    op.drop_table('write_logs')
    op.drop_table('source_files')
    op.drop_index('idx_sites_geom', table_name='sites', postgresql_using='gist')
    op.drop_table('sites')
    op.drop_table('scenarios')
    op.drop_table('plan_documents')
    op.drop_table('goals')
    op.drop_table('ai_enrichment')
    # ### end Alembic commands ###
